_target_: vp2.envs.og_env.OGEnv
a_dim: 7 # change to 4
camera_names: ${camera_names}
planning_modalities: ${planning_modalities}
randomize_lighting: False
randomize_color: False
renderer: igibson
renderer_camera_height: 256
renderer_camera_width: 256
camera_height: ${camera_height}
camera_width: ${camera_width}
shaped: False
magic_env: False
reset_xml: True

# Goal configs
goals_dataset: /code/small_grasp_dataset_test/dataset.hdf5
traj_start_idx: 0
use_final_goal_img: True
goal_ims_from_data: False