_target_: vp2.envs.robosuite_env.RobosuiteEnv
a_dim: 4
env_dataset: /viscam/projects/perceptual-metrics/robosuite/robosuite/models/assets/demonstrations/multi-scripted-ffix1k-2/demo.hdf5
camera_names: ${camera_names}
planning_modalities: ${planning_modalities}
randomize_lighting: False
randomize_color: False
renderer: igibson
renderer_camera_height: 256
renderer_camera_width: 256
camera_height: ${camera_height}
camera_width: ${camera_width}
shaped: False
magic_env: False
reset_xml: True

# Goal configs
goals_dataset: GOALS_DATASET_PATH_HERE/rendered_256.hdf5
traj_start_idx: -1
use_final_goal_img: True
goal_ims_from_data: False
