_target_: vp2.mpc.objectives.EnsembleObjective
objective:
  _target_: vp2.mpc.objectives.CombinedObjective
  objectives:
    rgb:
      _target_: vp2.mpc.objectives.SquaredError
      key: rgb
      weight: 0.5
    classifier:
      _target_: vp2.mpc.objectives.ClassifierReward
      key: rgb
      weight: 10
      checkpoint_directory: ???
agg: mean
lamb: 0
