defaults:
  - objective: mse_rgb
  - sampler: correlated_noise

_target_: vp2.mpc.mppi.MPPIOptimizer
a_dim: ${env.a_dim} # change to ${env.a_dim}
num_samples: 200 #200
horizon: ${planning_horizon}
gamma: 0.05
init_std: [0.03, 0.03, 0.03, 0.005, 0.005, 0.005, 0] #change to [0.05, 0.05, 0.05, 0.02, 0.02, 0.02, 0]
log_every: 1