defaults:
  - model: fitvid
  - agent: planning_agent
  - env: og #robosuite
  - sweep: single_task
#  - hydra/launcher: submitit_slurm

dataset: 
  dataset_file:
      - vp2/robosuite_benchmark_tasks/combined/5k_slice_rendered_256.hdf5 #vp2/robosuite_benchmark_tasks/combined/rendered_256.hdf5

seed: 0
num_processes: 16
num_trajectories: 1
max_traj_length: 13
n_context: 1
planning_horizon: 7 # 10 originally
camera_height: 64
camera_width: 64
run_name: default
resume: True

planning_modalities:
  - rgb


camera_names:
  - agentview_shift_2
model_name: default

hydra:
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed

